export const VIEW_LABELS = {
	coordinator: { en: 'Coordinator', es: 'Coordinador' },
	created: { en: 'Created', es: 'Creado' },
	status: { en: 'Status', es: 'Estado' },
	by: { en: 'by', es: 'por' },
	rejectionReason: { en: 'Rejection reason', es: 'Motivo de rechazo' },
	observation: { en: 'Observation', es: 'Observación' },
	export: { en: 'Export', es: 'Exportar' },
	sectionFindings: { en: 'Findings', es: 'Hallazgos' },
	sectionActions: { en: 'Actions', es: 'Acciones' },
	colCode: { en: 'Code', es: 'Código' },
	colDescription: { en: 'Description', es: 'Descripción' },
	colCriticality: { en: 'Criticality', es: 'Criticidad' },
	colCompleteness: { en: 'Completeness', es: 'Completitud' },
	colFinding: { en: 'Finding', es: 'Hallazgo' },
	btnSubmit: { en: 'Submit', es: 'Enviar' },
	btnEdit: { en: 'Edit', es: 'Editar' },
	btnApprove: { en: 'Approve', es: 'Aprobar' },
	btnReject: { en: 'Reject', es: 'Rechazar' },
	btnBack: { en: 'Back to list', es: 'Volver al listado' },
	rejectEmpty: {
		en: 'Observation is required to reject',
		es: 'La observación es obligatoria para rechazar',
	},
} as const;
