export const VIEW_LABELS = {
	coordinator: { en: 'Coordinator', es: 'Coordinador' },
	created: { en: 'Created', es: 'Creado' },
	status: { en: 'Status', es: 'Estado' },
	by: { en: 'by', es: 'por' },
	rejection_reason: { en: 'Rejection reason', es: 'Motivo de rechazo' },
	observation: { en: 'Observation', es: 'Observación' },
	export: { en: 'Export', es: 'Exportar' },
	section_findings: { en: 'Findings', es: 'Hallazgos' },
	section_actions: { en: 'Actions', es: 'Acciones' },
	col_code: { en: 'Code', es: 'Código' },
	col_description: { en: 'Description', es: 'Descripción' },
	col_criticality: { en: 'Criticality', es: 'Criticidad' },
	col_completeness: { en: 'Completeness', es: 'Completitud' },
	col_finding: { en: 'Finding', es: 'Hallazgo' },
	btn_submit: { en: 'Submit', es: 'Enviar' },
	btn_edit: { en: 'Edit', es: 'Editar' },
	btn_approve: { en: 'Approve', es: 'Aprobar' },
	btn_reject: { en: 'Reject', es: 'Rechazar' },
	btn_back: { en: 'Back to list', es: 'Volver al listado' },
	reject_empty: {
		en: 'Observation is required to reject',
		es: 'La observación es obligatoria para rechazar',
	},
} as const;
