export const PARAMETER_CODES = {
	LANGUAGES: 'PARAMETER_LANGUAGES',
	IFC_FIELDS: 'PARAMETER_IFC_FIELDS',
	IFC_NOTIFICATION_VARS: 'PARAMETER_IFC_NOTIFICATION_VARS',
	FINDING_PREFIX: 'PARAMETER_FINDING_PREFIX',
	ACTION_PREFIX: 'PARAMETER_ACTION_PREFIX',
} as const;
