export const API_TOKEN_MODULE_OPTIONS = [
	'HOME',
	'ADMIN',
	'USERS',
	'CORE',
	'ACADEMIC',
	'ACCREDITATION',
	'EVALUATION',
	'EVIDENCE',
	'IMPROVEMENT',
	'ORGANIZATION',
	'SURVEY',
	'IFCS',
	'IFC_FINDINGS',
	'RUBRICS',
	'TESTS',
	'LOADS',
	'PORTFOLIO',
	'SCRAPPING',
	'INTEGRATIONS',
] as const;

export const API_TOKEN_ACTION_OPTIONS = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'] as const;
